### ISSUE TITLE
Retrying sync fails since production workflow version exists

### ISSUE THREAD

**Issue by alexiswl** [umccr/cwl-ica#293]
```
2023-03-06 05:48:18,387 - INFO     - sync_github_actions       - __call__                                 : LineNo. 87   - Syncing "workflow" "umccrise-with-dragen-germline-pipeline/2.0.0--3.9.3" for project "production_workflows"
2023-03-06 05:48:19,390 - ERROR    - ica_workflow_version      - create_workflow_version                  : LineNo. 100  - Api exeception error when trying to create workflow version "wfl.7ed9c6014ac9498fbcbd4c17c28bc0d4/2.0.0--3.9.3--7b38ac8"
Traceback (most recent call last):
  File "/tmp/tmp.16vv4AaF57/cwl-ica/lib/python3.10/classes/ica_workflow_version.py", line 97, in create_workflow_version
    api_response = api_instance.create_workflow_version(self.ica_workflow_id, body=body)
  File "/tmp/tmp.16vv4AaF57/cwl-ica/lib/python3.10/site-packages/libica/openapi/libwes/api/workflow_versions_api.py", line 63, in create_workflow_version
    return self.create_workflow_version_with_http_info(workflow_id, **kwargs)  # noqa: E501
  File "/tmp/tmp.16vv4AaF57/cwl-ica/lib/python3.10/site-packages/libica/openapi/libwes/api/workflow_versions_api.py", line 146, in create_workflow_version_with_http_info
    return self.api_client.call_api(
  File "/tmp/tmp.16vv4AaF57/cwl-ica/lib/python3.10/site-packages/libica/openapi/libwes/api_client.py", line 364, in call_api
    return self.__call_api(resource_path, method,
  File "/tmp/tmp.16vv4AaF57/cwl-ica/lib/python3.10/site-packages/libica/openapi/libwes/api_client.py", line 188, in __call_api
    raise e
  File "/tmp/tmp.16vv4AaF57/cwl-ica/lib/python3.10/site-packages/libica/openapi/libwes/api_client.py", line 181, in __call_api
    response_data = self.request(
  File "/tmp/tmp.16vv4AaF57/cwl-ica/lib/python3.10/site-packages/libica/openapi/libwes/api_client.py", line 407, in request
    return self.rest_client.POST(url,
  File "/tmp/tmp.16vv4AaF57/cwl-ica/lib/python3.10/site-packages/libica/openapi/libwes/rest.py", line 265, in POST
    return self.request("POST", url,
  File "/tmp/tmp.16vv4AaF57/cwl-ica/lib/python3.10/site-packages/libica/openapi/libwes/rest.py", line 224, in request
    raise ApiException(http_resp=r)
libica.openapi.libwes.exceptions.ApiException: (409)
Reason: Conflict
HTTP response headers: HTTPHeaderDict({'Date': 'Mon, 06 Mar 2023 05:48:19 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'X-Frame-Options': 'deny', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Methods': 'GET, PUT, POST, DELETE, PATCH, OPTIONS', 'Access-Control-Allow-Headers': 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization'})
HTTP response body: {"code":"Workflows.VersionDefinition.WorkflowVersionAlreadyExists","message":"A workflow version definition with the given version '2.0.0--3.9.3--7b38ac8' already exists."}
```

**Comment by alexiswl** [comment]
Solution might be to just 'add-to-project.yaml'?
